# Generated by Django 3.2.8 on 2021-11-28 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lekarze',
            fields=[
                ('id_lekarze', models.IntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
                ('miejscowo', models.CharField(max_length=20)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('numer_telefonu', models.CharField(max_length=6)),
                ('Wyksztalcenie', models.CharField(max_length=20)),
                ('Specjalizacja', models.CharField(max_length=20)),
                ('PESEL', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Pacjenci',
            fields=[
                ('id_pacjenta', models.IntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
                ('miejscowo', models.CharField(max_length=20)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('numer_telefonu', models.CharField(max_length=9)),
                ('PESEL', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Wizyty',
            fields=[
                ('id_wizyty', models.IntegerField(primary_key=True, serialize=False)),
                ('data_wizyty', models.DateField()),
                ('godzina_wizyty', models.DateField()),
                ('Opis', models.CharField(max_length=20)),
                ('numer_recepty', models.IntegerField(max_length=20)),
                ('numer_skierowania', models.IntegerField(max_length=20)),
                ('id_lekarze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Przychodnia.lekarze')),
                ('id_pacjenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Przychodnia.pacjenci')),
            ],
        ),
    ]
