# Generated by Django 3.2.8 on 2021-11-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Przychodnia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizyty',
            name='godzina_wizyty',
            field=models.TimeField(),
        ),
    ]
