# Generated by Django 3.2.8 on 2021-11-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Przychodnia', '0002_alter_wizyty_godzina_wizyty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarze',
            name='numer_telefonu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pacjenci',
            name='numer_telefonu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wizyty',
            name='numer_recepty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wizyty',
            name='numer_skierowania',
            field=models.IntegerField(),
        ),
    ]
