# Generated by Django 3.2.8 on 2021-11-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Przychodnia', '0003_auto_20211130_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarze',
            name='id_lekarze',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pacjenci',
            name='id_pacjenta',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wizyty',
            name='id_wizyty',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
